// GENERATED from ../porto/frontend/src/store/translations.ts — do not hand-edit.
import Foundation

public struct LocalizedString: Sendable {
    public let th: String
    public let en: String
}

public enum Strings {
    public static let all: [String: LocalizedString] = [
        "common.addTx": LocalizedString(th: "+ เพิ่มรายการ", en: "+ Add Transaction"),
        "common.assetTypes.crypto": LocalizedString(th: "Crypto", en: "Crypto"),
        "common.assetTypes.deposit": LocalizedString(th: "เงินฝาก", en: "Cash/Deposits"),
        "common.assetTypes.fund": LocalizedString(th: "กองทุน", en: "Mutual Funds"),
        "common.assetTypes.th": LocalizedString(th: "หุ้นไทย", en: "Thai Stocks"),
        "common.assetTypes.us": LocalizedString(th: "หุ้น US", en: "US Stocks"),
        "common.cancel": LocalizedString(th: "ยกเลิก", en: "Cancel"),
        "common.debt": LocalizedString(th: "หนี้สิน", en: "Liabilities"),
        "common.delete": LocalizedString(th: "ลบ", en: "Delete"),
        "common.edit": LocalizedString(th: "แก้ไข", en: "Edit"),
        "common.error": LocalizedString(th: "เกิดข้อผิดพลาด", en: "Error occurred"),
        "common.loading": LocalizedString(th: "กำลังโหลด...", en: "Loading..."),
        "common.logout": LocalizedString(th: "ออกจากระบบ", en: "Logout"),
        "common.overview": LocalizedString(th: "ภาพรวม", en: "Overview"),
        "common.ports": LocalizedString(th: "พอร์ต", en: "Portfolios"),
        "common.save": LocalizedString(th: "บันทึก", en: "Save"),
        "common.settings": LocalizedString(th: "ตั้งค่า", en: "Settings"),
        "common.tx": LocalizedString(th: "Transactions", en: "Transactions"),
        "footer.clearAll": LocalizedString(th: "ล้างข้อมูลทั้งหมด", en: "Clear All Data"),
        "footer.clearError": LocalizedString(th: "เกิดข้อผิดพลาดในการล้างข้อมูล", en: "Error clearing data"),
        "footer.clearSuccess": LocalizedString(th: "ล้างข้อมูลทั้งหมดเรียบร้อยแล้ว", en: "Successfully cleared all data"),
        "footer.confirmClearAll": LocalizedString(th: "คุณต้องการลบข้อมูลการลงทุนและหนี้สินทั้งหมดของคุณใช่หรือไม่? (การดำเนินการนี้จะไม่สามารถย้อนกลับได้)", en: "Are you sure you want to delete all your investment and liability data? (This action cannot be undone)"),
        "footer.confirmLoadDemo": LocalizedString(th: "ระบบจะล็อกเอาท์ออกจากบัญชีนี้และเปิดบัญชีตัวอย่าง (Demo) แทน ยืนยันหรือไม่?", en: "The system will log you out of this account and open a Demo account instead. Confirm?"),
        "footer.demoError": LocalizedString(th: "เกิดข้อผิดพลาดในการโหลดเดโม", en: "Error loading demo"),
        "footer.loadDemo": LocalizedString(th: "โหลดข้อมูลตัวอย่าง", en: "Load Demo Data"),
        "footer.secureText": LocalizedString(th: "ข้อมูลทั้งหมดเก็บอย่างปลอดภัยในระบบฐานข้อมูลคลาวด์ส่วนตัวของคุณ · ราคาดึงผ่าน CoinGecko + Yahoo Finance", en: "All data is securely stored in your private cloud database · Prices retrieved via CoinGecko + Yahoo Finance"),
        "liabilities.addBtn": LocalizedString(th: "+ เพิ่มหนี้สิน", en: "+ Add Liability"),
        "liabilities.addFirstDebt": LocalizedString(th: "บันทึกหนี้สินของคุณเพื่อนำไปหักลบกับสินทรัพย์ในการคำนวณ Net Worth", en: "Record your liabilities to subtract from assets when calculating Net Worth."),
        "liabilities.catCar": LocalizedString(th: "สินเชื่อรถยนต์", en: "Auto Loan"),
        "liabilities.catCard": LocalizedString(th: "บัตรเครดิต", en: "Credit Card"),
        "liabilities.catHome": LocalizedString(th: "สินเชื่อบ้าน/อสังหาฯ", en: "Home Loan/Mortgage"),
        "liabilities.catOther": LocalizedString(th: "หนี้สินอื่นๆ", en: "Other Liabilities"),
        "liabilities.catPersonal": LocalizedString(th: "สินเชื่อส่วนบุคคล", en: "Personal Loan"),
        "liabilities.colBalance": LocalizedString(th: "ยอดคงเหลือ", en: "Balance"),
        "liabilities.colCat": LocalizedString(th: "ประเภท", en: "Category"),
        "liabilities.colInterest": LocalizedString(th: "ดอกเบี้ย (%)", en: "Interest (%)"),
        "liabilities.colMonthly": LocalizedString(th: "ผ่อนชำระ/เดือน", en: "Monthly Pay"),
        "liabilities.colName": LocalizedString(th: "ชื่อรายการ", en: "Liability Name"),
        "liabilities.colUpdated": LocalizedString(th: "อัปเดตล่าสุด", en: "Last Updated"),
        "liabilities.confirmDeleteDebt": LocalizedString(th: "คุณต้องการลบรายการหนี้สินนี้ใช่หรือไม่?", en: "Are you sure you want to delete this liability?"),
        "liabilities.deleteSuccess": LocalizedString(th: "ลบหนี้สินเรียบร้อยแล้ว", en: "Liability deleted successfully"),
        "liabilities.loadingLiabilities": LocalizedString(th: "กำลังโหลดข้อมูลหนี้สิน…", en: "Loading liabilities..."),
        "liabilities.monthlyPayment": LocalizedString(th: "ยอดผ่อนชำระต่อเดือน", en: "Total Monthly Payment"),
        "liabilities.noDebt": LocalizedString(th: "ยังไม่มีบันทึกรายการหนี้สิน", en: "No liabilities recorded yet"),
        "liabilities.title": LocalizedString(th: "การจัดการหนี้สิน (Liabilities)", en: "Liabilities Management"),
        "liabilities.totalDebt": LocalizedString(th: "ยอดหนี้สินรวมทั้งหมด", en: "Total Outstanding Debt"),
        "login.demoBtn": LocalizedString(th: "เข้าใช้งานแบบเดโม", en: "Access Demo Mode"),
        "login.desc": LocalizedString(th: "Crypto · หุ้นไทย · หุ้น US · กองทุน · เงินฝาก — รวมทุกพอร์ต คำนวณ Net Worth และกำไร-ขาดทุนแบบเรียลไทม์ ราคาสดจาก CoinGecko + Yahoo Finance", en: "Crypto · Thai Stocks · US Stocks · Funds · Deposits — consolidate all portfolios, calculate Net Worth and P&L in real-time. Live prices from CoinGecko + Yahoo Finance"),
        "login.emailInvalid": LocalizedString(th: "อีเมลไม่ถูกต้อง", en: "Invalid email address"),
        "login.emailLabel": LocalizedString(th: "อีเมล", en: "Email"),
        "login.featuresAssets": LocalizedString(th: "5 ประเภทสินทรัพย์", en: "5 Asset Classes"),
        "login.featuresPorts": LocalizedString(th: "พอร์ตไม่จำกัด", en: "Unlimited Portfolios"),
        "login.featuresSecure": LocalizedString(th: "เก็บข้อมูลปลอดภัย 100%", en: "100% Secure Storage"),
        "login.hasAccount": LocalizedString(th: "มีบัญชีอยู่แล้ว?", en: "Already have an account?"),
        "login.loadingLogin": LocalizedString(th: "กำลังเข้าสู่ระบบ…", en: "Signing in..."),
        "login.loginBtn": LocalizedString(th: "เข้าสู่ระบบ", en: "Log In"),
        "login.loginDesc": LocalizedString(th: "เข้าสู่ระบบเพื่อดูพอร์ตการลงทุนของคุณ", en: "Sign in to view your portfolios"),
        "login.loginTitle": LocalizedString(th: "ยินดีต้อนรับกลับ", en: "Welcome Back"),
        "login.nameLabel": LocalizedString(th: "ชื่อ", en: "Name"),
        "login.namePlaceholder": LocalizedString(th: "ชื่อของคุณ", en: "Your Name"),
        "login.nameRequired": LocalizedString(th: "กรุณากรอกชื่อของคุณ", en: "Please enter your name"),
        "login.noAccount": LocalizedString(th: "ยังไม่มีบัญชี?", en: "Don't have an account?"),
        "login.orText": LocalizedString(th: "หรือ", en: "OR"),
        "login.passwordLabel": LocalizedString(th: "รหัสผ่าน", en: "Password"),
        "login.passwordMinLength": LocalizedString(th: "รหัสผ่านต้องมีอย่างน้อย 4 ตัวอักษร", en: "Password must be at least 4 characters long"),
        "login.secureNote": LocalizedString(th: "ข้อมูลบัญชีและรายการทั้งหมดจะถูกเก็บอย่างปลอดภัยบนระบบฐานข้อมูลคลาวด์แยกสำหรับพอร์ตส่วนตัวของคุณ", en: "All account data and transactions are securely stored on a separate cloud database for your private portfolio."),
        "login.signupBtn": LocalizedString(th: "สร้างบัญชีใหม่", en: "Sign Up"),
        "login.signupDesc": LocalizedString(th: "ตั้งค่าบัญชีเพื่อเริ่มติดตามพอร์ตของคุณ", en: "Setup your account to start tracking portfolios"),
        "login.signupDisabled": LocalizedString(th: "ระบบปิดการลงทะเบียนบัญชีใหม่ชั่วคราว", en: "New account registration is temporarily disabled"),
        "login.signupTitle": LocalizedString(th: "สร้างบัญชีใหม่", en: "Create New Account"),
        "login.title": LocalizedString(th: "ติดตามความมั่งคั่งของคุณในที่เดียว", en: "Track Your Wealth in One Place"),
        "modals.asset.addSuccess": LocalizedString(th: "เพิ่มสินทรัพย์สำเร็จ", en: "Asset added successfully"),
        "modals.asset.createTitle": LocalizedString(th: "เพิ่มสินทรัพย์ใหม่ในพอร์ต", en: "Add New Asset to Portfolio"),
        "modals.asset.currencyLabel": LocalizedString(th: "สกุลเงินอ้างอิง *", en: "Reference Currency *"),
        "modals.asset.currencyRequired": LocalizedString(th: "กรุณาเลือกสกุลเงิน", en: "Please select a currency"),
        "modals.asset.editTitle": LocalizedString(th: "แก้ไขข้อมูลสินทรัพย์", en: "Edit Asset Details"),
        "modals.asset.infoBoxCrypto": LocalizedString(th: "สัญลักษณ์ต้องตรงกับ CoinGecko Coin ID เช่น bitcoin, ethereum, cardano (ค้นหาด้วย lowercase)", en: "Symbol must match CoinGecko Coin ID (e.g. bitcoin, ethereum, cardano in lowercase)"),
        "modals.asset.infoBoxDeposit": LocalizedString(th: "เงินฝาก/เงินสด ใช้สัญลักษณ์อะไรก็ได้ และกำหนดมูลค่าจากการใส่รายการธุรกรรม (ฝาก/ถอน)", en: "Cash/deposits can use any symbol, and total amount is updated via transactions (deposit/withdraw)"),
        "modals.asset.infoBoxFund": LocalizedString(th: "กองทุนไทยใช้สัญลักษณ์ย่อปกติ เช่น B-CHINE-EQ, ONE-UGG-RA (ดึงราคาปิดรายวัน)", en: "Thai mutual funds use abbreviation symbols (e.g. B-CHINE-EQ, ONE-UGG-RA)"),
        "modals.asset.infoBoxStockTh": LocalizedString(th: "หุ้นไทยให้ต่อท้ายด้วย .BK เช่น PTT.BK, ADVANC.BK", en: "Thai stocks should end with .BK (e.g. PTT.BK, ADVANC.BK)"),
        "modals.asset.infoBoxStockUs": LocalizedString(th: "หุ้น US ใช้สัญลักษณ์มาตรฐานของตลาด เช่น AAPL, TSLA, MSFT", en: "US stocks use standard symbols (e.g. AAPL, TSLA, MSFT)"),
        "modals.asset.nameLabel": LocalizedString(th: "ชื่อสินทรัพย์ (ภาษาไทย/อังกฤษ) *", en: "Asset Name (Thai/English) *"),
        "modals.asset.namePlaceholder": LocalizedString(th: "เช่น Bitcoin, หุ้นซีพี ออลล์, Apple Inc.", en: "e.g. Bitcoin, CP ALL, Apple"),
        "modals.asset.nameRequired": LocalizedString(th: "กรุณากรอกชื่อสินทรัพย์", en: "Please enter an asset name"),
        "modals.asset.noteLabel": LocalizedString(th: "บันทึกเพิ่มเติม (ทางเลือก)", en: "Notes (Optional)"),
        "modals.asset.notePlaceholder": LocalizedString(th: "รายละเอียดความเสี่ยง หรือเป้าหมายพอร์ต", en: "Risk details or target allocations"),
        "modals.asset.portLabel": LocalizedString(th: "พอร์ตลงทุน *", en: "Portfolio *"),
        "modals.asset.portRequired": LocalizedString(th: "กรุณาเลือกพอร์ต", en: "Please select a portfolio"),
        "modals.asset.saveSuccess": LocalizedString(th: "บันทึกสินทรัพย์สำเร็จ", en: "Asset saved successfully"),
        "modals.asset.submitAdd": LocalizedString(th: "เพิ่มสินทรัพย์", en: "Add Asset"),
        "modals.asset.submitSave": LocalizedString(th: "บันทึกการเปลี่ยนแปลง", en: "Save Changes"),
        "modals.asset.symbolLabel": LocalizedString(th: "สัญลักษณ์ (Symbol) *", en: "Symbol *"),
        "modals.asset.symbolPlaceholder": LocalizedString(th: "เช่น BTC, CPALL, AAPL, B-CHINE-EQ", en: "e.g. BTC, CPALL, AAPL"),
        "modals.asset.symbolRequired": LocalizedString(th: "กรุณากรอกสัญลักษณ์", en: "Please enter a symbol"),
        "modals.asset.typeLabel": LocalizedString(th: "ประเภทสินทรัพย์ *", en: "Asset Type *"),
        "modals.asset.typeRequired": LocalizedString(th: "กรุณาเลือกประเภทสินทรัพย์", en: "Please select an asset type"),
        "modals.chart.closeBtn": LocalizedString(th: "ปิดหน้าต่าง", en: "Close"),
        "modals.chart.currencyLabel": LocalizedString(th: "สกุลเงินของสินทรัพย์", en: "Asset Currency"),
        "modals.chart.last60Days": LocalizedString(th: "ประวัติราคา 60 วันล่าสุด", en: "Last 60 Days Price Chart"),
        "modals.chart.noHistory": LocalizedString(th: "ไม่มีข้อมูลประวัติราคาย้อนหลังสำหรับสินทรัพย์นี้", en: "No historical price data found for this asset."),
        "modals.chart.title": LocalizedString(th: "ประวัติราคาของ", en: "Price History of"),
        "modals.liability.addSuccess": LocalizedString(th: "เพิ่มรายการหนี้สำเร็จ", en: "Liability added successfully"),
        "modals.liability.balanceLabel": LocalizedString(th: "ยอดหนี้คงเหลือปัจจุบัน *", en: "Current Outstanding Balance *"),
        "modals.liability.balanceRequired": LocalizedString(th: "กรุณากรอกยอดหนี้คงเหลือ", en: "Please enter outstanding balance"),
        "modals.liability.catLabel": LocalizedString(th: "ประเภทหนี้สิน *", en: "Liability Category *"),
        "modals.liability.catRequired": LocalizedString(th: "กรุณาเลือกประเภทหนี้สิน", en: "Please select a category"),
        "modals.liability.createTitle": LocalizedString(th: "เพิ่มรายการหนี้สินใหม่", en: "Add New Liability"),
        "modals.liability.editTitle": LocalizedString(th: "แก้ไขข้อมูลหนี้สิน", en: "Edit Liability Details"),
        "modals.liability.interestLabel": LocalizedString(th: "อัตราดอกเบี้ยต่อปี (%)", en: "Annual Interest Rate (%)"),
        "modals.liability.monthlyLabel": LocalizedString(th: "ยอดผ่อนชำระต่อเดือน *", en: "Monthly Payment *"),
        "modals.liability.monthlyRequired": LocalizedString(th: "กรุณากรอกยอดผ่อนชำระต่อเดือน", en: "Please enter monthly payment"),
        "modals.liability.nameLabel": LocalizedString(th: "ชื่อรายการหนี้สิน *", en: "Liability Name *"),
        "modals.liability.namePlaceholder": LocalizedString(th: "เช่น สินเชื่อบ้าน ธอส, บัตรเครดิต Citi", en: "e.g. GHB Home Loan, Citi Credit Card"),
        "modals.liability.nameRequired": LocalizedString(th: "กรุณากรอกชื่อรายการหนี้สิน", en: "Please enter a name"),
        "modals.liability.saveSuccess": LocalizedString(th: "แก้ไขรายการหนี้สำเร็จ", en: "Liability updated successfully"),
        "modals.liability.submitAdd": LocalizedString(th: "เพิ่มรายการหนี้", en: "Add Liability"),
        "modals.liability.submitSave": LocalizedString(th: "บันทึกหนี้สิน", en: "Save Liability"),
        "modals.price.currencyLabel": LocalizedString(th: "สกุลเงิน", en: "Currency"),
        "modals.price.currentPriceLabel": LocalizedString(th: "ราคาปัจจุบันอ้างอิงสด", en: "Live Reference Price"),
        "modals.price.newPriceLabel": LocalizedString(th: "ราคาใหม่ (แมนนวล) *", en: "New Price (Manual) *"),
        "modals.price.priceMin": LocalizedString(th: "ราคาต้องมากกว่าหรือเท่ากับ 0", en: "Price must be greater than or equal to 0"),
        "modals.price.priceRequired": LocalizedString(th: "กรุณากรอกราคาใหม่", en: "Please enter the new price"),
        "modals.price.submitBtn": LocalizedString(th: "อัปเดตราคา", en: "Update Price"),
        "modals.price.success": LocalizedString(th: "อัปเดตราคาสำเร็จ", en: "Price updated successfully"),
        "modals.price.symbolLabel": LocalizedString(th: "สัญลักษณ์ (Symbol)", en: "Symbol"),
        "modals.price.title": LocalizedString(th: "อัปเดตราคาสินทรัพย์แมนนวล", en: "Manual Price Update"),
        "modals.transaction.addSuccess": LocalizedString(th: "เพิ่มรายการธุรกรรมสำเร็จ", en: "Transaction recorded successfully"),
        "modals.transaction.assetLabel": LocalizedString(th: "สินทรัพย์อ้างอิง *", en: "Select Asset *"),
        "modals.transaction.assetRequired": LocalizedString(th: "กรุณาเลือกสินทรัพย์", en: "Please select an asset"),
        "modals.transaction.dateLabel": LocalizedString(th: "วันที่ทำรายการ *", en: "Transaction Date *"),
        "modals.transaction.dateRequired": LocalizedString(th: "กรุณาเลือกวันที่", en: "Please select transaction date"),
        "modals.transaction.noAssetsWarning": LocalizedString(th: "ยังไม่มีสินทรัพย์ในระบบ กรุณาเพิ่มสินทรัพย์ก่อนลงรายการซื้อขาย", en: "No assets in system. Please add an asset first before recording transactions."),
        "modals.transaction.priceLabel": LocalizedString(th: "ราคาต่อหน่วย (สกุลเงินของสินทรัพย์นั้น) *", en: "Price per Unit (Asset Currency) *"),
        "modals.transaction.priceMin": LocalizedString(th: "ราคาต้องมากกว่าหรือเท่ากับ 0", en: "Price must be greater than or equal to 0"),
        "modals.transaction.pricePlaceholder": LocalizedString(th: "เช่น 95000, 62.50, 1.00", en: "e.g. 95000, 62.50, 1.00"),
        "modals.transaction.priceRequired": LocalizedString(th: "กรุณากรอกราคาต่อหน่วย", en: "Please enter unit price"),
        "modals.transaction.qtyLabel": LocalizedString(th: "จำนวนหน่วย *", en: "Quantity *"),
        "modals.transaction.qtyMin": LocalizedString(th: "จำนวนต้องมากกว่า 0", en: "Quantity must be greater than 0"),
        "modals.transaction.qtyPlaceholder": LocalizedString(th: "เช่น 0.05, 100, 5000", en: "e.g. 0.05, 100, 5000"),
        "modals.transaction.qtyRequired": LocalizedString(th: "กรุณากรอกจำนวนหน่วย", en: "Please enter quantity"),
        "modals.transaction.selectAssetPlaceholder": LocalizedString(th: "-- เลือกสินทรัพย์ --", en: "-- Select Asset --"),
        "modals.transaction.submitBtn": LocalizedString(th: "บันทึกรายการ", en: "Save Transaction"),
        "modals.transaction.title": LocalizedString(th: "บันทึกรายการธุรกรรม (Transaction)", en: "Record Transaction"),
        "modals.transaction.typeBuy": LocalizedString(th: "ซื้อ (BUY) / ฝาก (DEPOSIT)", en: "BUY / DEPOSIT"),
        "modals.transaction.typeLabel": LocalizedString(th: "ประเภทธุรกรรม *", en: "Transaction Type *"),
        "modals.transaction.typeSell": LocalizedString(th: "ขาย (SELL) / ถอน (WITHDRAW)", en: "SELL / WITHDRAW"),
        "overview.allAssets": LocalizedString(th: "ตารางสินทรัพย์ทั้งหมด", en: "All Assets Table"),
        "overview.assetOverview": LocalizedString(th: "ภาพรวมสินทรัพย์", en: "Asset Overview"),
        "overview.assetsLabel": LocalizedString(th: "สินทรัพย์", en: "Assets"),
        "overview.assetsVsLiabilities": LocalizedString(th: "Assets vs Liabilities", en: "Assets vs Liabilities"),
        "overview.createPort": LocalizedString(th: "+ สร้างพอร์ต", en: "+ Create Portfolio"),
        "overview.debtNoteBad": LocalizedString(th: "สูง — ควรเร่งลดหนี้", en: "High — reduce debt recommended"),
        "overview.debtNoteGood": LocalizedString(th: "อยู่ในเกณฑ์ดีมาก", en: "Excellent condition"),
        "overview.debtNoteWarn": LocalizedString(th: "พอใช้ — ระวังอย่าให้เกิน 50%", en: "Fair — avoid exceeding 50%"),
        "overview.debtRatio": LocalizedString(th: "อัตราหนี้ต่อสินทรัพย์", en: "Debt-to-Asset Ratio"),
        "overview.emptyDesc": LocalizedString(th: "เริ่มต้นด้วยการสร้างพอร์ตและบันทึกสินทรัพย์แรกของคุณ หรือคลิกปุ่มด้านล่างเพื่อสร้างบัญชีเดโมและเซ็ตข้อมูลตัวอย่าง", en: "Start by creating a portfolio and recording your first asset, or click the button below to load demo data."),
        "overview.emptyTitle": LocalizedString(th: "ยังไม่มีสินทรัพย์ในพอร์ต", en: "No assets in portfolio yet"),
        "overview.gainers": LocalizedString(th: "ขึ้นแรง", en: "Gainers"),
        "overview.itemsCount": LocalizedString(th: "รายการ", en: "items"),
        "overview.liabilities": LocalizedString(th: "Liabilities", en: "Liabilities"),
        "overview.liabilitiesLabel": LocalizedString(th: "หนี้สิน", en: "Liabilities"),
        "overview.loadingOverview": LocalizedString(th: "กำลังโหลดข้อมูลภาพรวม…", en: "Loading overview data..."),
        "overview.losers": LocalizedString(th: "ลงแรง", en: "Losers"),
        "overview.monthAbbr": LocalizedString(th: "เดือนนี้", en: "this month"),
        "overview.netWorth": LocalizedString(th: "ความมั่งคั่งสุทธิของคุณ (Net Worth)", en: "Your Net Worth"),
        "overview.netWorthGrowth": LocalizedString(th: "การเติบโตของ Net Worth", en: "Net Worth Growth"),
        "overview.noUnrealizedPl": LocalizedString(th: "ยังไม่มีการทำกำไร/ขาดทุน", en: "No unrealized profit/loss yet"),
        "overview.pctOfTotalAssets": LocalizedString(th: "ของสินทรัพย์รวม", en: "of total assets"),
        "overview.portsAllocation": LocalizedString(th: "สัดส่วนตามพอร์ต", en: "Allocation by Portfolio"),
        "overview.portsCount": LocalizedString(th: "พอร์ต", en: "portfolios"),
        "overview.sortedByValue": LocalizedString(th: "เรียงตามมูลค่า", en: "sorted by value"),
        "overview.table30d": LocalizedString(th: "30 วัน", en: "30d"),
        "overview.tableAsset": LocalizedString(th: "สินทรัพย์", en: "Asset"),
        "overview.tablePort": LocalizedString(th: "พอร์ต", en: "Portfolio"),
        "overview.tablePrice": LocalizedString(th: "ราคา", en: "Price"),
        "overview.tableToday": LocalizedString(th: "วันนี้", en: "Today"),
        "overview.tableTotalReturn": LocalizedString(th: "กำไรรวม", en: "Total Return"),
        "overview.tableValue": LocalizedString(th: "มูลค่า", en: "Value"),
        "overview.tableWeight": LocalizedString(th: "น้ำหนัก", en: "Weight"),
        "overview.todayPl": LocalizedString(th: "P/L วันนี้", en: "Today's P/L"),
        "overview.topMovers": LocalizedString(th: "Top Movers วันนี้", en: "Today's Top Movers"),
        "overview.totalAssets": LocalizedString(th: "Total Assets", en: "Total Assets"),
        "overview.totalLabel": LocalizedString(th: "รวม", en: "Total"),
        "overview.treemapLegend": LocalizedString(th: "กลุ่ม = พอร์ต · สี = พอร์ต · ขนาด = มูลค่า", en: "Group = Portfolio · Color = Portfolio · Size = Value"),
        "overview.typeAllocation": LocalizedString(th: "สัดส่วนตามประเภทสินทรัพย์", en: "Allocation by Asset Type"),
        "overview.unrealizedPl": LocalizedString(th: "กำไร / ขาดทุน รายสินทรัพย์ (Unrealized)", en: "Unrealized P/L by Asset"),
        "overview.updatedText": LocalizedString(th: "อัปเดตล่าสุด · CoinGecko + Yahoo Finance", en: "Last updated · CoinGecko + Yahoo Finance"),
        "portfolios.addAssetBtn": LocalizedString(th: "+ เพิ่มสินทรัพย์", en: "+ Add Asset"),
        "portfolios.addFirstPort": LocalizedString(th: "สร้างพอร์ตแรกของคุณเพื่อจัดกลุ่มสินทรัพย์", en: "Create your first portfolio to group your assets."),
        "portfolios.confirmDelete": LocalizedString(th: "คุณต้องการลบพอร์ตนี้ใช่หรือไม่? สินทรัพย์ทั้งหมดในพอร์ตนี้จะถูกลบไปด้วย!", en: "Are you sure you want to delete this portfolio? All assets in this portfolio will also be deleted!"),
        "portfolios.createBtn": LocalizedString(th: "+ สร้างพอร์ต", en: "+ Create Portfolio"),
        "portfolios.createPortTitle": LocalizedString(th: "สร้างพอร์ตใหม่", en: "Create New Portfolio"),
        "portfolios.createSuccess": LocalizedString(th: "สร้างพอร์ตใหม่เรียบร้อยแล้ว", en: "Portfolio created successfully"),
        "portfolios.deleteSuccess": LocalizedString(th: "ลบพอร์ตเรียบร้อยแล้ว", en: "Portfolio deleted successfully"),
        "portfolios.editPortTitle": LocalizedString(th: "แก้ไขพอร์ตการลงทุน", en: "Edit Portfolio"),
        "portfolios.nameRequired": LocalizedString(th: "กรุณากรอกชื่อพอร์ต", en: "Please enter a portfolio name"),
        "portfolios.noAssetsInPort": LocalizedString(th: "ยังไม่มีสินทรัพย์ในพอร์ตนี้", en: "No assets in this portfolio yet."),
        "portfolios.noPorts": LocalizedString(th: "ยังไม่มีพอร์ตการลงทุน", en: "No portfolios yet"),
        "portfolios.placeholderDesc": LocalizedString(th: "ระบุคำอธิบายสั้นๆ ของพอร์ตนี้", en: "Enter a short description of this portfolio"),
        "portfolios.placeholderName": LocalizedString(th: "เช่น เก็บออม, ลงทุนระยะยาว, Gamble", en: "e.g. Savings, Long-term, Gamble"),
        "portfolios.portColorLabel": LocalizedString(th: "สีของพอร์ต", en: "Portfolio Color"),
        "portfolios.portDescLabel": LocalizedString(th: "คำอธิบาย (ทางเลือก)", en: "Description (Optional)"),
        "portfolios.portNameLabel": LocalizedString(th: "ชื่อพอร์ต", en: "Portfolio Name"),
        "portfolios.saveSuccess": LocalizedString(th: "บันทึกพอร์ตเรียบร้อยแล้ว", en: "Portfolio saved successfully"),
        "portfolios.tableAvgCost": LocalizedString(th: "ทุนเฉลี่ย", en: "Avg Cost"),
        "portfolios.tableName": LocalizedString(th: "ชื่อสินทรัพย์", en: "Asset Name"),
        "portfolios.tablePl": LocalizedString(th: "กำไร/ขาดทุน", en: "P/L"),
        "portfolios.tablePrice": LocalizedString(th: "ราคาปัจจุบัน", en: "Live Price"),
        "portfolios.tableQty": LocalizedString(th: "จำนวนที่ถือ", en: "Quantity"),
        "portfolios.tableSymbol": LocalizedString(th: "สัญลักษณ์", en: "Symbol"),
        "portfolios.tableType": LocalizedString(th: "ประเภท", en: "Type"),
        "portfolios.tableValue": LocalizedString(th: "มูลค่ารวม", en: "Total Value"),
        "portfolios.title": LocalizedString(th: "การจัดการพอร์ตการลงทุน", en: "Portfolio Management"),
        "portfolios.totalPortCost": LocalizedString(th: "ทุนรวม", en: "Total Cost"),
        "portfolios.totalPortValue": LocalizedString(th: "มูลค่าพอร์ตรวม", en: "Total Portfolio Value"),
        "settings.active": LocalizedString(th: "ใช้งานอยู่", en: "Active"),
        "settings.backupDesc": LocalizedString(th: "ดาวน์โหลดข้อมูลทั้งหมดของคุณ หรือกู้คืนจากไฟล์ (เข้ารหัสด้วยรหัสผ่าน)", en: "Download all your data, or restore from file (Encrypted with password)"),
        "settings.backupLabel": LocalizedString(th: "สำรองข้อมูล (Data Backup)", en: "Data Backup"),
        "settings.cancel": LocalizedString(th: "ยกเลิก", en: "Cancel"),
        "settings.exportBtn": LocalizedString(th: "ส่งออก", en: "Export"),
        "settings.exportDesc": LocalizedString(th: "ตั้งรหัสผ่าน 8 ตัวอักษรขึ้นไปเพื่อเข้ารหัสไฟล์ สำคัญ: ต้องจำรหัสผ่านให้ได้เพื่อใช้ตอนนำเข้า", en: "Set a password (min 8 characters) to encrypt the file. Important: You must remember it to import later."),
        "settings.exportTitle": LocalizedString(th: "ส่งออกข้อมูล (Export)", en: "Export Data"),
        "settings.fileLabel": LocalizedString(th: "ไฟล์ Backup (.porto)", en: "Backup File (.porto)"),
        "settings.importBtn": LocalizedString(th: "นำเข้า", en: "Import"),
        "settings.importDesc": LocalizedString(th: "อัปโหลดไฟล์ .porto และใส่รหัสผ่านที่ใช้ตอนส่งออก ข้อมูลปัจจุบันจะถูกเขียนทับ", en: "Upload .porto file and enter the password used during export. Current data will be overwritten."),
        "settings.importTitle": LocalizedString(th: "นำเข้าข้อมูล (Import)", en: "Import Data"),
        "settings.importWarn": LocalizedString(th: "ระวัง! การนำเข้าจะลบข้อมูลปัจจุบันทั้งหมดและแทนที่ด้วยข้อมูลจากไฟล์", en: "Warning! Importing will delete all current data and replace it with data from the file."),
        "settings.passwordLabel": LocalizedString(th: "รหัสผ่าน (8 ตัวอักษรขึ้นไป)", en: "Password (min 8 chars)"),
        "settings.processing": LocalizedString(th: "กำลังดำเนินการ...", en: "Processing..."),
        "settings.subtitle": LocalizedString(th: "เลือกธีมสีของแอป — มีผลทันทีทั้งหน้าจอ และจำค่าไว้ในเบราว์เซอร์ของคุณ", en: "Choose the app theme — applies instantly across the screen and is remembered in your browser"),
        "settings.themeCount": LocalizedString(th: "3 ธีมเริ่มต้น", en: "3 built-in themes"),
        "settings.themeLabel": LocalizedString(th: "ธีม (Theme)", en: "Theme"),
        "settings.title": LocalizedString(th: "ตั้งค่า", en: "Settings"),
        "transactions.colActions": LocalizedString(th: "จัดการ", en: "Actions"),
        "transactions.colAsset": LocalizedString(th: "สินทรัพย์", en: "Asset"),
        "transactions.colDate": LocalizedString(th: "วันที่", en: "Date"),
        "transactions.colNetAmt": LocalizedString(th: "มูลค่าสุทธิ", en: "Net Amount"),
        "transactions.colPort": LocalizedString(th: "พอร์ต", en: "Portfolio"),
        "transactions.colPrice": LocalizedString(th: "ราคาต่อหน่วย", en: "Price"),
        "transactions.colQty": LocalizedString(th: "จำนวน", en: "Qty"),
        "transactions.colType": LocalizedString(th: "ประเภท", en: "Type"),
        "transactions.confirmDeleteTx": LocalizedString(th: "คุณต้องการลบรายการธุรกรรมนี้ใช่หรือไม่? ระบบจะปรับปรุงจำนวนสินทรัพย์โดยอัตโนมัติ", en: "Are you sure you want to delete this transaction? The system will automatically recalculate asset quantities."),
        "transactions.deleteTxSuccess": LocalizedString(th: "ลบรายการสำเร็จ", en: "Transaction deleted successfully"),
        "transactions.filterAllPorts": LocalizedString(th: "ทุกพอร์ต", en: "All Portfolios"),
        "transactions.filterAllTypes": LocalizedString(th: "ทุกประเภทสินทรัพย์", en: "All Asset Types"),
        "transactions.loadingTx": LocalizedString(th: "กำลังโหลดรายการธุรกรรม…", en: "Loading transactions..."),
        "transactions.noTx": LocalizedString(th: "ไม่พบรายการธุรกรรม", en: "No transactions found"),
        "transactions.recordBtn": LocalizedString(th: "+ บันทึกรายการ", en: "+ Record Transaction"),
        "transactions.title": LocalizedString(th: "บันทึกรายการซื้อขาย (Transactions)", en: "Transaction History"),
        "transactions.txBuy": LocalizedString(th: "ซื้อ", en: "BUY"),
        "transactions.txSell": LocalizedString(th: "ขาย", en: "SELL"),
    ]
}
